<script lang="ts">
import type { PrimitiveProps } from '@/Primitive';

export interface FieldControlProps extends PrimitiveProps {
  /** Id of the element. Falls back to the id generated by the ancestor `FieldRoot`. */
  id?: string;
  /** The controlled value of the control. Can be bound with `v-model`. */
  modelValue?: string | number;
  /** The value of the control when it is initially rendered. Use when you do not need to control its value. */
  defaultValue?: string | number;
}

export type FieldControlEmits = {
  /** Event handler called when the value of the control changes. */
  'update:modelValue': [value: string];
};
</script>

<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, useAttrs, watch } from 'vue';
import { Primitive } from '@/Primitive';
import { useForwardExpose } from '@/shared';
import { injectFieldRootContext } from './FieldRoot.vue';

defineOptions({
  inheritAttrs: false,
});

const props = withDefaults(defineProps<FieldControlProps>(), {
  as: 'input',
  modelValue: undefined,
  defaultValue: undefined,
});
const emits = defineEmits<FieldControlEmits>();

const fieldContext = injectFieldRootContext();
const attrs = useAttrs();

const { forwardRef, currentElement } = useForwardExpose();

const controlId = computed(() => props.id ?? fieldContext.fieldId.value);

// A boolean attribute is present unless omitted or explicitly `false`
// (`<FieldControl required>` passes `''`).
function isAttrSet(value: unknown) {
  return value !== undefined && value !== false && value !== 'false';
}

// Merge, don't overwrite: consumer-provided ids are combined with the field's.
function mergeIds(consumerValue: unknown, fieldValue: string | undefined) {
  return [consumerValue as string | undefined, fieldValue].filter(Boolean).join(' ') || undefined;
}

// `attrs` isn't reactive, so everything derived from it is computed during
// render (which re-runs whenever the parent passes new attributes) rather
// than cached in a `computed`.
//
// The field's `name` takes precedence; `disabled`/`required` apply when set on
// either the field or the control; a consumer-provided `aria-invalid` wins,
// and a disabled control is never invalid. The rest of the consumer's
// attributes pass through untouched.
function getBindings() {
  const {
    'aria-describedby': describedBy,
    'aria-labelledby': labelledBy,
    'aria-invalid': ariaInvalid,
    name,
    disabled,
    required,
    ...rest
  } = attrs;
  const isDisabled = fieldContext.disabled.value || isAttrSet(disabled);
  return {
    ...fieldContext.dataAttributes.value,
    ...rest,
    ...valueBinding.value,
    'name': fieldContext.name.value ?? name as string | undefined,
    'disabled': isDisabled || undefined,
    'required': (fieldContext.required.value || isAttrSet(required)) || undefined,
    'aria-labelledby': mergeIds(labelledBy, fieldContext.labelId.value),
    'aria-describedby': mergeIds(describedBy, fieldContext.describedBy.value),
    'aria-invalid': ariaInvalid ?? ((fieldContext.invalid.value && !isDisabled) || undefined),
  };
}

// Only bind `value` when controlled or given a default, so a plain
// `value` attribute (or no value at all) keeps working natively.
const isControlled = computed(() => props.modelValue !== undefined);
const valueBinding = computed(() => {
  if (isControlled.value) {
    return { value: props.modelValue };
  }
  if (props.defaultValue !== undefined) {
    return { value: props.defaultValue };
  }
  return {};
});

type NativeControl = HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement;

function getElement() {
  const element = currentElement.value as HTMLElement | undefined;
  return element && ['INPUT', 'TEXTAREA', 'SELECT'].includes(element.tagName)
    ? element as NativeControl
    : undefined;
}

function handleInput() {
  const element = getElement();
  if (element) {
    emits('update:modelValue', element.value);
  }
  // A controlled value reaches the field through the `modelValue` watcher
  // instead, so a value the consumer rejects or rewrites never does.
  if (!isControlled.value) {
    fieldContext.handleControlInput();
  }
}

// Flushed after render, so the element's value (and validity) is up to date.
watch(() => props.modelValue, (value, previous) => {
  if (value !== undefined && value !== previous) {
    fieldContext.handleControlInput({ value: String(value) });
  }
}, { flush: 'post' });

let unregister: (() => void) | undefined;
onMounted(() => {
  unregister = fieldContext.registerControl({
    id: () => controlId.value,
    element: () => currentElement.value as HTMLElement | undefined,
    // Always read the live DOM value: programmatic writes (a direct `.value`
    // assignment, autofill) don't fire `input`.
    getValue: () => getElement()?.value,
    validityElement: getElement,
  });
});
onBeforeUnmount(() => unregister?.());
</script>

<template>
  <Primitive
    :id="controlId"
    :ref="forwardRef"
    v-bind="getBindings()"
    :as="as"
    :as-child="asChild"
    @focus="fieldContext.handleControlFocus()"
    @blur="fieldContext.handleControlBlur()"
    @input="handleInput"
  >
    <slot />
  </Primitive>
</template>
