name: Setup
description: Installs Node and caches pnpm.

runs:
  using: composite

  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Setup Node.js environment
      uses: actions/setup-node@v6
      with:
        node-version: 20.19.4
        registry-url: 'https://registry.npmjs.org'
        cache: pnpm

    - name: Install dependencies
      shell: bash
      run: pnpm i --frozen-lockfile
