packages:
  - packages/*
  - playground/*
  - docs
  - .histoire

catalog:
  '@commitlint/cli': ^19.8.1
  '@commitlint/config-conventional': ^19.8.1
  '@floating-ui/dom': ^1.6.13
  '@floating-ui/vue': ^1.1.6
  '@histoire/plugin-vue': ^0.17.17
  '@iconify/json': ^2.2.330
  '@iconify/vue': ^4.3.0
  '@internationalized/date': ^3.8.0
  '@internationalized/number': ^3.6.0
  '@nuxt/kit': ^3.16.2
  '@nuxt/schema': ^3.16.2
  '@playwright/test': ^1.51.0
  '@radix-ui/colors': ^3.0.0
  '@rollup/plugin-alias': ^5.1.1
  '@tanstack/vue-virtual': ^3.13.4
  '@testing-library/dom': ^10.4.1
  '@testing-library/jest-dom': ^6.6.4
  '@testing-library/user-event': ^14.6.1
  '@testing-library/vue': ^8.1.0
  '@tsconfig/node18': ^18.2.4
  '@types/jsdom': ^21.1.7
  '@types/node': ^24.0.13
  '@unocss/nuxt': ^66.3.3
  '@unocss/vite': ^66.3.3
  '@vinicunca/eslint-config': ^3.18.0
  '@vinicunca/perkakas': ^1.6.0
  '@vinicunca/unocss-preset': ^1.16.1
  '@vitejs/plugin-vue': ^6.0.1
  '@vitest/coverage-istanbul': ^3.2.4
  '@vue/test-utils': ^2.4.6
  '@vue/tsconfig': ^0.7.0
  '@vueuse/core': 12.5.0
  '@vueuse/shared': 12.5.0
  aria-hidden: ^1.2.4
  bumpp: ^10.2.0
  defu: ^6.1.4
  eslint: ^9.31.0
  histoire: ^0.17.17
  jsdom: ^26.1.0
  lint-staged: ^16.1.2
  mark.js: ^8.11.1
  minisearch: ^7.1.2
  nuxt: ^3.16.2
  postcss-preset-env: ^10.2.4
  simple-git-hooks: ^2.13.0
  taze: ^19.1.0
  tsdown: ^0.12.9
  tsx: ^4.20.3
  typescript: ^5.8.3
  unbuild: ^3.5.0
  unocss: ^66.3.3
  unplugin-vue-components: ^28.4.1
  vite: ^7.0.6
  vite-plugin-dts: ^4.5.4
  vitepress: ^1.6.3
  vitest: ^3.2.4
  vitest-axe: 0.1.0
  vitest-canvas-mock: ^0.3.3
  vue: 3.5.17
  vue-component-type-helpers: ^3.0.3
  vue-router: ^4.5.0
  vue-tsc: ^2.2.12

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
