packages:
  - packages/*
  - docs
  - .histoire
  - packages/pohon/playgrounds/nuxt
  - packages/pohon/playgrounds/vue
overrides:
  vite: ^7.1.5

catalogs:
  base:
    '@commitlint/cli': ^19.8.1
    '@commitlint/config-conventional': ^19.8.1
    '@vinicunca/eslint-config': 3.26.0
    bumpp: ^10.2.3
    eslint: ^9.36.0
    eslint-plugin-format: ^1.0.2
    lint-staged: ^16.1.6
    simple-git-hooks: ^2.13.1
    taze: ^19.7.0
    tsx: ^4.20.5
    typescript: 5.9.2
    unocss: 66.5.1
    vue-router: ^4.5.1
  core:
    '@floating-ui/dom': ^1.7.4
    '@floating-ui/vue': ^1.1.9
    '@iconify/vue': ^5.0.0
    '@internationalized/date': ^3.8.2
    '@internationalized/number': ^3.6.5
    '@tanstack/vue-virtual': ^3.13.12
    '@testing-library/dom': ^10.4.1
    '@testing-library/jest-dom': ^6.8.0
    '@testing-library/user-event': ^14.6.1
    '@testing-library/vue': ^8.1.0
    '@tsconfig/node18': ^18.2.4
    '@types/jsdom': ^21.1.7
    '@types/node': ^24.3.1
    '@vinicunca/perkakas': ^1.7.1
    '@vitejs/plugin-vue': ^6.0.1
    '@vitest/coverage-istanbul': ^3.2.4
    '@vue/test-utils': ^2.4.6
    '@vue/tsconfig': ^0.8.1
    '@vueuse/core': 12.8.2
    '@vueuse/shared': 12.8.2
    aria-hidden: ^1.2.6
    defu: ^6.1.4
    jsdom: ^26.1.0
    tsdown: ^0.12.9
    vite: ^7.1.5
    vitest: ^3.2.4
    vitest-axe: 0.1.0
    vitest-canvas-mock: ^0.3.3
    vue: 3.5.21
    vue-component-type-helpers: ^3.0.6
    vue-tsc: 2.2.12
  docs:
    '@nuxt/content': ^3.7.0
    '@nuxt/image': ^1.11.0
    '@vinicunca/unocss-preset': ^1.23.0
    better-sqlite3: ^12.2.0
    nuxt-component-meta: ^0.14.0
    nuxt-og-image: ^5.1.9
    shiki-transformer-color-highlight: ^1.0.0
  histoire:
    '@histoire/plugin-vue': ^0.17.17
    '@rollup/plugin-alias': ^5.1.1
    histoire: ^0.17.17
  plugins:
    '@nuxt/kit': 4.0.3
    '@nuxt/schema': 4.0.3
    unbuild: ^3.6.1
    unplugin-vue-components: ^29.0.0
  pohon:
    '@nuxt/module-builder': ^1.0.1
    '@unocss/nuxt': 66.5.1
    nuxt: 4.0.3
    unocss-variants: ^1.0.0
ignoredBuiltDependencies:
  - '@parcel/watcher'
  - unrs-resolver
  - vue-demi
onlyBuiltDependencies:
  - better-sqlite3
  - esbuild
  - sharp
  - simple-git-hooks
  - unrs-resolver
resolutions:
  pohon: workspace:*
  unplugin: ^2.3.10
