packages:
  - 'packages/*'
  - docs
  - .histoire
patchedDependencies:
  vitepress@1.6.3: patches/vitepress@1.6.3.patch
catalogs:
  base:
    '@commitlint/cli': ^19.8.1
    '@commitlint/config-conventional': ^19.8.1
    '@vinicunca/eslint-config': ^3.22.0
    bumpp: ^10.2.3
    eslint: ^9.34.0
    eslint-plugin-format: ^1.0.1
    lint-staged: ^16.1.5
    simple-git-hooks: ^2.13.1
    tsx: ^4.20.5
    typescript: 5.8.3
    unocss: ^66.4.2
  core:
    '@floating-ui/dom': ^1.7.3
    '@floating-ui/vue': ^1.1.8
    '@iconify/vue': ^5.0.0
    '@internationalized/date': ^3.8.2
    '@internationalized/number': ^3.6.4
    '@tanstack/vue-virtual': ^3.13.12
    '@testing-library/dom': ^10.4.1
    '@testing-library/jest-dom': ^6.8.0
    '@testing-library/user-event': ^14.6.1
    '@testing-library/vue': ^8.1.0
    '@tsconfig/node18': ^18.2.4
    '@types/jsdom': ^21.1.7
    '@types/node': ^24.3.0
    '@vinicunca/perkakas': ^1.7.1
    '@vitejs/plugin-vue': ^6.0.1
    '@vitest/coverage-istanbul': ^3.2.4
    '@vue/test-utils': ^2.4.6
    '@vue/tsconfig': ^0.8.0
    '@vueuse/core': 12.5.0
    '@vueuse/shared': 12.5.0
    aria-hidden: ^1.2.6
    defu: ^6.1.4
    jsdom: ^26.1.0
    tsdown: ^0.12.9
    vite: ^7.1.3
    vitest: ^3.2.4
    vitest-axe: 0.1.0
    vitest-canvas-mock: ^0.3.3
    vue: 3.5.17
    vue-component-type-helpers: ^3.0.5
    vue-tsc: 2.2.12
  docs:
    '@babel/traverse': ^7.26.7
    '@iconify/json': ^2.2.367
    '@stackblitz/sdk': ^1.11.0
    '@types/babel__traverse': ^7.20.6
    '@types/hast': ^3.0.4
    '@types/markdown-it': ^14.1.2
    '@vinicunca/unocss-preset': ^1.20.1
    autoprefixer: ^10.4.20
    codesandbox: ^2.2.3
    fast-glob: ^3.3.3
    hast: ^1.0.0
    mark.js: ^8.11.1
    markdown-it: ^14.1.0
    markdown-it-anchor: ^9.2.0
    minisearch: ^6.3.0
    shiki: ^1.29.2
    vitepress: 1.6.3
    vue-component-meta: ^2.2.12
  histoire:
    '@histoire/plugin-vue': ^0.17.17
    '@rollup/plugin-alias': ^5.1.1
    histoire: ^0.17.17
  plugins:
    '@nuxt/kit': ^3.15.4
    '@nuxt/schema': ^3.15.4
    unbuild: ^2.0.0
    unplugin-vue-components: ^0.28.0
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
