packages:
  - packages/*
  - docs
  - packages/pohon/playgrounds/nuxt
  - packages/pohon/playgrounds/vue

shamefullyHoist: true
autoInstallPeers: true
ignoreWorkspaceRootCheck: true

overrides:
  akar: workspace:*
  pohon-ui: workspace:*
  # There's a weird issue within rolldown where when building akar not all components are included in the build. Since all the deps are hoisted, nuxt deps uses a newer version of rolldown therefore causing that particular issue. #TODO: Remove this when rolldown is fixed
  rolldown: 1.0.0-beta.26
  unplugin: ^2.3.10
  vite: ^7.1.9

catalogs:
  base:
    '@commitlint/cli': ^19.8.1
    '@commitlint/config-conventional': ^19.8.1
    '@iconify/json': ^2.2.389
    '@vinicunca/eslint-config': 3.28.0
    bumpp: ^10.2.3
    eslint: ^9.36.0
    eslint-plugin-format: ^1.0.2
    lint-staged: ^16.2.0
    simple-git-hooks: ^2.13.1
    taze: ^19.7.0
    tsx: ^4.20.5
    typescript: 5.9.2
    unocss: 66.5.3
    vue-router: ^4.5.1
  core:
    '@floating-ui/dom': ^1.7.4
    '@floating-ui/vue': ^1.1.9
    '@iconify/vue': ^5.0.0
    '@internationalized/date': ^3.9.0
    '@internationalized/number': ^3.6.5
    '@tanstack/vue-virtual': ^3.13.12
    '@testing-library/dom': ^10.4.1
    '@testing-library/jest-dom': ^6.8.0
    '@testing-library/user-event': ^14.6.1
    '@testing-library/vue': ^8.1.0
    '@tsconfig/node18': ^18.2.4
    '@types/jsdom': ^21.1.7
    '@types/node': ^24.3.3
    '@vinicunca/perkakas': ^1.7.1
    '@vitejs/plugin-vue': ^6.0.1
    '@vitest/coverage-istanbul': ^3.2.4
    '@vue/test-utils': ^2.4.6
    '@vue/tsconfig': ^0.8.1
    '@vueuse/core': 13.9.0
    '@vueuse/integrations': 13.9.0
    '@vueuse/shared': 13.9.0
    aria-hidden: ^1.2.6
    defu: ^6.1.4
    happy-dom: ^20.0.0
    jsdom: ^27.0.0
    tsdown: ^0.12.9
    vite: ^7.1.9
    vitest: ^3.2.4
    vitest-axe: 0.1.0
    vitest-canvas-mock: ^0.3.3
    vue: 3.5.21
    vue-component-type-helpers: 3.1.1
    vue-tsc: 3.1.1
  docs:
    '@babel/traverse': ^7.28.4
    '@nuxt/image': ^1.11.0
    '@types/babel__traverse': ^7.28.0
    '@vinicunca/unocss-preset': 1.29.1
    better-sqlite3: ^12.2.0
    fast-glob: ^3.3.3
    nuxt-component-meta: ^0.14.0
    nuxt-og-image: ^5.1.11
    prettier: ^3.6.2
    shiki-transformer-color-highlight: ^1.0.0
    vue-component-meta: ^3.1.0
  plugins:
    '@nuxt/kit': 4.1.2
    '@nuxt/schema': 4.1.2
    unbuild: ^3.6.1
    unplugin-vue-components: ^29.1.0
  pohon:
    '@nuxt/content': ^3.7.0
    '@nuxt/fonts': ^0.11.4
    '@nuxt/icon': ^2.0.0
    '@nuxt/module-builder': ^1.0.1
    '@nuxt/test-utils': ^3.19.2
    '@nuxtjs/color-mode': ^3.5.2
    '@standard-schema/spec': ^1.0.0
    '@tanstack/vue-table': ^8.21.3
    '@unocss/nuxt': 66.5.3
    colortranslator: ^5.0.0
    embla-carousel-auto-height: ^8.6.0
    embla-carousel-auto-scroll: ^8.6.0
    embla-carousel-autoplay: ^8.6.0
    embla-carousel-class-names: ^8.6.0
    embla-carousel-fade: ^8.6.0
    embla-carousel-vue: ^8.6.0
    embla-carousel-wheel-gestures: ^8.1.0
    fuse.js: ^7.1.0
    hookable: ^5.5.3
    magic-string: ^0.30.19
    mlly: ^1.8.0
    motion-v: ^1.7.1
    nuxt: 4.1.2
    ohash: ^2.0.11
    pathe: ^2.0.3
    tinyglobby: ^0.2.15
    unocss-variants: ^1.0.0
    unplugin: ^2.3.10
    unplugin-auto-import: ^20.1.0
    zod: ^4.1.11
ignoredBuiltDependencies:
  - '@parcel/watcher'
  - unrs-resolver
  - vue-demi
onlyBuiltDependencies:
  - better-sqlite3
  - esbuild
  - sharp
  - simple-git-hooks
  - unrs-resolver
