packages:
  - packages/*
  - playground/*
  - docs
  - .histoire
catalog:
  '@commitlint/cli': ^19.8.0
  '@commitlint/config-conventional': ^19.8.0
  '@floating-ui/dom': ^1.6.13
  '@floating-ui/vue': ^1.1.6
  '@histoire/plugin-vue': ^0.17.17
  '@iconify/json': ^2.2.316
  '@iconify/vue': ^4.3.0
  '@internationalized/date': ^3.7.0
  '@internationalized/number': ^3.6.0
  '@nuxt/kit': ^3.16.0
  '@nuxt/schema': ^3.16.0
  '@playwright/test': ^1.51.0
  '@radix-ui/colors': ^3.0.0
  '@rollup/plugin-alias': ^5.1.1
  '@tanstack/vue-virtual': ^3.13.4
  '@testing-library/dom': ^10.4.0
  '@testing-library/jest-dom': ^6.6.3
  '@testing-library/user-event': ^14.6.1
  '@testing-library/vue': ^8.1.0
  '@tsconfig/node18': ^18.2.4
  '@types/node': ^22.13.10
  '@unocss/nuxt': ^66.0.0
  '@unocss/vite': ^66.0.0
  '@vinicunca/eslint-config': ^3.8.0
  '@vinicunca/perkakas': ^1.4.0
  '@vinicunca/unocss-preset': ^1.9.0
  '@vitejs/plugin-vue': ^5.2.1
  '@vitejs/plugin-vue-jsx': ^4.1.1
  '@vitest/coverage-istanbul': ^3.0.8
  '@vue/test-utils': ^2.4.6
  '@vue/tsconfig': ^0.7.0
  '@vueuse/core': 12.5.0
  '@vueuse/shared': 12.5.0
  aria-hidden: ^1.2.4
  bumpp: ^10.1.0
  defu: ^6.1.4
  eslint: ^9.22.0
  histoire: ^0.17.17
  jsdom: ^26.0.0
  lint-staged: ^15.5.0
  mark.js: ^8.11.1
  minisearch: ^7.1.2
  nuxt: ^3.16.0
  pnpm: 10.4.0
  postcss-preset-env: ^10.1.5
  rimraf: ^6.0.1
  simple-git-hooks: ^2.11.1
  taze: ^19.0.2
  tsx: ^4.19.3
  typescript: ^5.8.2
  unbuild: ^3.5.0
  unocss: ^66.0.0
  unplugin-vue-components: ^28.4.1
  vite: ^6.2.1
  vite-plugin-dts: ^4.5.3
  vitepress: ^1.6.3
  vitest: ^3.0.8
  vitest-axe: 0.1.0
  vitest-canvas-mock: ^0.3.3
  vue: 3.5.13
  vue-component-type-helpers: ^2.2.8
  vue-router: ^4.5.0
  vue-tsc: ^2.1.6
