shellEmulator: true

packages:
  - 'packages/*'
  - docs

allowBuilds:
  esbuild: false
  simple-git-hooks: false
  vue-demi: false

overrides:
  minimatch@>=5.0.0 <5.1.8: '>=5.1.8'
  picomatch@<2.3.2: '>=2.3.2'
  rollup@>=3.0.0 <3.30.0: '>=3.30.0'
  rollup@>=4.0.0 <4.59.0: '>=4.59.0'
  svgo@>=3.0.0 <3.3.3: '>=3.3.3'

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
  - vue-demi
