catalog:
  '@commitlint/cli': ^19.3.0
  '@commitlint/config-conventional': ^19.2.2
  '@floating-ui/dom': ^1.6.11
  '@floating-ui/vue': ^1.1.5
  '@histoire/plugin-vue': ^0.17.17
  '@iconify/json': ^2.2.276
  '@iconify/vue': ^4.1.2
  '@internationalized/date': ^3.5.6
  '@internationalized/number': ^3.5.4
  '@radix-ui/colors': ^3.0.0
  '@rollup/plugin-alias': ^5.1.0
  '@tanstack/vue-virtual': ^3.10.8
  '@testing-library/dom': ^10.4.0
  '@testing-library/jest-dom': ^6.5.0
  '@testing-library/user-event': ^14.5.2
  '@testing-library/vue': ^8.1.0
  '@tsconfig/node18': ^18.2.4
  '@types/node': ^20.14.9
  '@unocss/vite': ^0.65.1
  '@vinicunca/eslint-config': ^2.15.1
  '@vinicunca/unocss-preset': ^1.0.0
  '@vitejs/plugin-vue': ^5.1.4
  '@vitejs/plugin-vue-jsx': ^4.0.1
  '@vitest/coverage-istanbul': ^2.1.1
  '@vue/test-utils': ^2.4.6
  '@vue/tsconfig': ^0.5.1
  '@vueuse/core': ^12.0.0
  '@vueuse/shared': ^12.0.0
  aria-hidden: ^1.2.4
  bumpp: ^9.4.1
  defu: ^6.1.4
  eslint: ^9.16.0
  histoire: ^0.17.17
  jsdom: ^25.0.1
  lint-staged: ^15.2.10
  ohash: ^1.1.4
  pnpm: ^9.4.0
  rimraf: ^6.0.1
  simple-git-hooks: ^2.11.1
  taze: ^0.18.0
  tsx: ^4.16.0
  typescript: 5.3.3
  uncrypto: ^0.1.3
  unocss: ^0.65.1
  vite: ^5.4.8
  vite-plugin-dts: ^4.2.3
  vitest: ^2.1.1
  vitest-axe: 0.1.0
  vitest-canvas-mock: ^0.3.3
  vue: 3.5.13
  vue-component-type-helpers: ^2.1.6
  vue-tsc: 2.1.6
packages:
  - packages/*
  - playground/*
  - docs
  - .histoire
