shellEmulator: true

packages:
  - packages/*
  - docs
  - packages/pohon/playgrounds/nuxt
  - packages/pohon/playgrounds/vue
  - packages/pohon/playgrounds/admin

onlyBuiltDependencies:
  - better-sqlite3
  - puppeteer
  - sharp
  - simple-git-hooks
  - esbuild
  - unrs-resolver
  - vue-demi
