catalog:
  '@commitlint/cli': ^19.6.0
  '@commitlint/config-conventional': ^19.6.0
  '@floating-ui/dom': ^1.6.12
  '@floating-ui/vue': ^1.1.5
  '@histoire/plugin-vue': ^0.17.17
  '@iconify/json': ^2.2.284
  '@iconify/vue': ^4.2.0
  '@internationalized/date': ^3.6.0
  '@internationalized/number': ^3.6.0
  '@nuxt/kit': ^3.14.1592
  '@nuxt/schema': ^3.14.1592
  '@radix-ui/colors': ^3.0.0
  '@rollup/plugin-alias': ^5.1.0
  '@tanstack/vue-virtual': ^3.11.2
  '@testing-library/dom': ^10.4.0
  '@testing-library/jest-dom': ^6.6.3
  '@testing-library/user-event': ^14.5.2
  '@testing-library/vue': ^8.1.0
  '@tsconfig/node18': ^18.2.4
  '@types/node': ^20.14.9
  '@unocss/nuxt': ^0.65.1
  '@unocss/vite': ^0.65.1
  '@vinicunca/eslint-config': ^2.15.1
  '@vinicunca/perkakas': ^1.2.0
  '@vinicunca/unocss-preset': ^1.0.1
  '@vitejs/plugin-vue': ^5.2.1
  '@vitejs/plugin-vue-jsx': ^4.1.1
  '@vitest/coverage-istanbul': ^2.1.8
  '@vue/test-utils': ^2.4.6
  '@vue/tsconfig': ^0.5.1
  '@vueuse/core': ^12.0.0
  '@vueuse/shared': ^12.0.0
  aria-hidden: ^1.2.4
  bumpp: ^9.4.1
  defu: ^6.1.4
  eslint: ^9.16.0
  histoire: ^0.17.17
  jsdom: ^25.0.1
  lint-staged: ^15.2.10
  nuxt: ^3.14.1592
  ohash: ^1.1.4
  pnpm: ^9.15.0
  rimraf: ^6.0.1
  simple-git-hooks: ^2.11.1
  taze: ^0.18.0
  tsx: ^4.19.2
  typescript: ^5.7.2
  unbuild: ^3.0.1
  uncrypto: ^0.1.3
  unocss: ^0.65.1
  unplugin-vue-components: ^0.28.0
  vite: ^6.0.3
  vite-plugin-dts: ^4.3.0
  vitest: ^2.1.8
  vitest-axe: 0.1.0
  vitest-canvas-mock: ^0.3.3
  vue: 3.5.13
  vue-component-type-helpers: ^2.1.6
  vue-tsc: 2.1.6
packages:
  - packages/*
  - playground/*
  - docs
  - .histoire
