packages:
  - 'packages/*'
  - docs
patchedDependencies:
  vitepress@1.6.3: patches/vitepress@1.6.3.patch
catalogs:
  base:
    '@commitlint/cli': ^19.8.1
    '@commitlint/config-conventional': ^19.8.1
    '@vinicunca/eslint-config': ^3.21.0
    bumpp: ^10.2.2
    eslint: ^9.32.0
    eslint-plugin-format: ^1.0.1
    lint-staged: ^16.1.4
    simple-git-hooks: ^2.13.1
    tsx: ^4.20.3
    typescript: 5.8.3
  core:
    '@floating-ui/dom': ^1.6.13
    '@floating-ui/vue': ^1.1.6
    '@iconify/vue': ^4.3.0
    '@internationalized/date': ^3.7.0
    '@internationalized/number': ^3.6.0
    '@tanstack/vue-virtual': ^3.12.0
    '@testing-library/dom': ^10.4.1
    '@testing-library/jest-dom': ^6.6.4
    '@testing-library/user-event': ^14.6.1
    '@testing-library/vue': ^8.1.0
    '@tsconfig/node18': ^18.2.4
    '@types/jsdom': ^21.1.7
    '@types/node': ^24.0.13
    '@vinicunca/perkakas': ^1.7.1
    '@vitejs/plugin-vue': ^6.0.1
    '@vitest/coverage-istanbul': ^3.2.4
    '@vue/test-utils': ^2.4.6
    '@vue/tsconfig': ^0.7.0
    '@vueuse/core': 12.5.0
    '@vueuse/shared': 12.5.0
    aria-hidden: ^1.2.4
    defu: ^6.1.4
    jsdom: ^26.1.0
    tsdown: ^0.12.9
    vite: ^7.0.6
    vitest: ^3.2.4
    vitest-axe: 0.1.0
    vitest-canvas-mock: ^0.3.3
    vue: 3.5.17
    vue-component-type-helpers: ^3.0.3
    vue-tsc: 2.2.12
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
