catalog:
  '@commitlint/cli': ^19.6.1
  '@commitlint/config-conventional': ^19.6.0
  '@floating-ui/dom': ^1.6.13
  '@floating-ui/vue': ^1.1.6
  '@histoire/plugin-vue': ^0.17.17
  '@iconify/json': ^2.2.299
  '@iconify/vue': ^4.3.0
  '@internationalized/date': ^3.7.0
  '@internationalized/number': ^3.6.0
  '@nuxt/kit': ^3.15.3
  '@nuxt/schema': ^3.15.3
  '@radix-ui/colors': ^3.0.0
  '@rollup/plugin-alias': ^5.1.1
  '@tanstack/vue-virtual': ^3.11.2
  '@testing-library/dom': ^10.4.0
  '@testing-library/jest-dom': ^6.6.3
  '@testing-library/user-event': ^14.6.1
  '@testing-library/vue': ^8.1.0
  '@tsconfig/node18': ^18.2.4
  '@types/node': ^22.10.10
  '@unocss/nuxt': ^65.4.3
  '@unocss/vite': ^65.4.3
  '@vinicunca/eslint-config': ^3.0.0
  '@vinicunca/perkakas': ^1.2.3
  '@vinicunca/unocss-preset': ^1.1.4
  '@vitejs/plugin-vue': ^5.2.1
  '@vitejs/plugin-vue-jsx': ^4.1.1
  '@vitest/coverage-istanbul': ^3.0.4
  '@vue/test-utils': ^2.4.6
  '@vue/tsconfig': ^0.7.0
  '@vueuse/core': ^12.5.0
  '@vueuse/shared': ^12.5.0
  aria-hidden: ^1.2.4
  bumpp: ^10.0.1
  defu: ^6.1.4
  eslint: ^9.19.0
  histoire: ^0.17.17
  jsdom: ^26.0.0
  lint-staged: ^15.4.3
  nuxt: ^3.15.3
  ohash: ^1.1.4
  pnpm: ^9.15.4
  rimraf: ^6.0.1
  simple-git-hooks: ^2.11.1
  taze: ^18.3.0
  tsx: ^4.19.2
  typescript: ^5.7.3
  unbuild: ^3.3.1
  unocss: ^65.4.3
  unplugin-vue-components: ^28.0.0
  vite: ^6.0.11
  vite-plugin-dts: ^4.5.0
  vitest: ^3.0.4
  vitest-axe: 0.1.0
  vitest-canvas-mock: ^0.3.3
  vue: 3.5.13
  vue-component-type-helpers: ^2.2.0
  vue-tsc: 2.1.6
packages:
  - packages/*
  - playground/*
  - docs
  - .histoire
