shellEmulator: true

packages:
  - 'packages/*'
  - docs
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
  - vue-demi
allowBuilds:
  esbuild: false
  simple-git-hooks: false
  vue-demi: false
