import type { PreferencesCore } from './preferences.entity';
import { P_DASHBOARD_LAYOUT } from 'pohon-ui/utils/dashboard';

export const defaultPreferences: PreferencesCore = {
  app: {
    accessMode: 'frontend',
    checkUpdatesInterval: 1,
    enableColorGrayMode: false,
    enableColorWeakMode: false,
    enableCompact: false,
    contentCompact: 'wide',
    contentCompactWidth: 1200,
    contentPadding: 0,
    contentPaddingBottom: 0,
    contentPaddingLeft: 0,
    contentPaddingRight: 0,
    contentPaddingTop: 0,
    defaultAvatar: '',
    defaultHomePath: '/admin/dashboard/analytics',
    enableDynamicTitle: true,
    enableCheckUpdates: true,
    enablePreferences: true,
    enableRefreshToken: false,
    isMobile: false,
    layout: P_DASHBOARD_LAYOUT.SIDEBAR_NAV,
    locale: 'en-US',
    loginExpiredMode: 'page',
    name: 'Vinicunca Admin',
    preferencesButtonPosition: 'auto',
    enableWatermark: false,
    zIndex: 200,
  },
  breadcrumb: {
    enable: true,
    hideOnlyOne: false,
    showHome: false,
    showIcon: true,
    styleType: 'normal',
  },
  copyright: {
    companyName: 'Vinicunca',
    companySiteLink: 'https://vinicunca.dev',
    date: '2024',
    enable: true,
    icp: '',
    icpLink: '',
    showSetting: true,
  },
  footer: {
    enable: false,
    isFixed: false,
    height: 32,
  },
  header: {
    enable: true,
    height: 50,
    hidden: false,
    menuAlign: 'start',
    mode: 'fixed',
  },
  logo: {
    enable: true,
    fit: 'contain',
    source: 'https://raw.githubusercontent.com/vinicunca/static-resources/refs/heads/main/logo-3d.webp',
  },
  navigation: {
    isAccordion: false,
    isSplit: true,
    styleType: 'rounded',
  },
  shortcutKeys: {
    enable: true,
    enableGlobalLockScreen: true,
    enableGlobalLogout: true,
    enableGlobalPreferences: true,
    enableGlobalSearch: true,
  },
  sidebar: {
    autoActivateChild: false,
    collapsed: false,
    showCollapsedButton: true,
    collapsedShowTitle: false,
    collapsedWidth: 60,
    enable: true,
    expandChildrenOnHover: true,
    extraCollapsed: true,
    extraCollapsedWidth: 60,
    showFixedButton: true,
    hidden: false,
    mixedWidth: 80,
    width: 300,
  },
  tabbar: {
    isDraggable: true,
    enable: true,
    height: 38,
    enableKeepAlive: true,
    maxCount: 0,
    isMiddleClickToClose: false,
    enablePersist: true,
    showIcon: true,
    showMaximize: true,
    showMore: true,
    showRefresh: true,
    styleType: 'chrome',
    enableWheelable: true,
  },
  theme: {
    builtinType: 'default',
    colorDestructive: 'hsl(348 100% 61%)',
    colorPrimary: 'hsl(212 100% 45%)',
    colorSuccess: 'hsl(144 57% 58%)',
    colorWarning: 'hsl(42 84% 61%)',
    mode: 'light',
    radius: '0.5',
    enableSemiDarkHeader: false,
    enableSemiDarkSidebar: false,
  },
  transition: {
    enable: true,
    enableLoading: true,
    name: 'fade-slide',
    enableProgress: true,
  },
  widget: {
    enableFullscreen: true,
    enableGlobalSearch: true,
    enableLanguageToggle: true,
    enableLockScreen: true,
    enableNotification: true,
    showRefresh: true,
    showSidebarToggle: true,
    showThemeToggle: true,
    showTimezone: false,
  },
};
