import { toSentenceCase } from '@vinicunca/perkakas';

const components = [
  'accordion',
  'alert',
  'avatar',
  'badge',
  'banner',
  'breadcrumb',
  'button',
  'calendar',
  'card',
  'carousel',
  'checkbox-group',
  'checkbox',
  'chip',
  'collapsible',
  'color-mode',
  'color-picker',
  'command-palette',
  'context-menu',
  'dialog',
  'drawer',
  'dropdown-menu',
  'empty',
  'error',
  'field-group',
  'file-upload',
  'footer',
  'form-field',
  'form',
  'header',
  'input-menu',
  'input-number',
  'input-tags',
  'input',
  'kbd',
  'link',
  'locale',
  'marquee',
  'navigation-menu',
  'pagination',
  'pin-input',
  'popover',
  'progress',
  'radio-group',
  'select-menu',
  'select',
  'separator',
  'shortcuts',
  'skeleton',
  'slideover',
  'slider',
  'stepper',
  'switch',
  'table',
  'tabs',
  'textarea',
  'timeline',
  'toast',
  'tooltip',
  'tree',
].map((component) => ({
  label: toSentenceCase(component.split('/').pop() as string),
  icon: 'i-lucide-box',
  to: `/components/${component}`,
}));

export function useNavigation() {
  const items = [
    { label: 'Home', icon: 'i-lucide-home', to: '/' },
    // { label: 'Chat', icon: 'i-lucide-message-circle', to: '/chat' },
  ];

  return {
    items,
    components,
  };
}
