import type { RouteRecordRaw } from 'vue-router';
import { toTitleCase } from '@vinicunca/perkakas';

const COMPONENTS = [
  'accordion',
  'alert',
  'avatar',
  'badge',
  'banner',
  'breadcrumb',
  'button',
  'calendar',
  'card',
  'carousel',
  'checkbox-group',
  'checkbox',
  'chip',
  'collapsible',
  'color-mode',
  'color-picker',
  'command-palette',
  'context-menu',
  'dialog',
  'drawer',
  'dropdown-menu',
  'editable',
  'empty',
  'error',
  'field-group',
  'file-upload',
  'footer',
  'form-field',
  'form',
  'header',
  'input-date',
  'input-menu',
  'input-number',
  'input-tags',
  'input-time',
  'input',
  'kbd',
  'link',
  'listbox',
  'locale',
  'marquee',
  'navigation-menu',
  'pagination',
  'pin-input',
  'popover',
  'progress',
  'radio-group',
  'scroll-area',
  'select-menu',
  'select',
  'separator',
  'shortcuts',
  'skeleton',
  'slideover',
  'slider',
  'splitter',
  'stepper',
  'switch',
  'table',
  'tabs',
  'textarea',
  'timeline',
  'toast',
  'toggle-group',
  'tooltip',
  'tree',
];

const routes: Array<RouteRecordRaw> = [
  {
    meta: {
      icon: 'i-lucide:box',
      order: -1,
      title: 'Pohon Components',
    },
    name: 'Pohon Components',
    path: '/admin/pohon-components',
    children: COMPONENTS.map((component) => ({
      name: component,
      path: `/admin/pohon-components/${component}`,
      component: () => import(`../pages/pohon/${component}.vue`),
      meta: {
        title: toTitleCase(component),
      },
    })),
  },
];

export default routes;
