name: Typo check

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  typo:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v5

      - name: Writes changes in the local checkout
        uses: crate-ci/typos@master
